### PR TITLE
ReadableStream read all Stash Data

### PR DESCRIPTION
**Pull request by TamalesEnMiPinata**
Fix for the problem where the page does not reload and fill the form: The data that comes back from your Stash instance is returned as a ReadableStream and when the read() method is called on it the data is not necessarily complete, it's just whatever is in the buffer of the ReadableStream. This works fine for the smaller messages that basically just have the status of "Uploading Images" etc, but for the actual payload of the data the buffer often does not contain the entire set of data returned from Stash.

This fix assumes that the data coming back from Stash is the last set of "chunks" of data from the ReadableStream. If the data is not read entirely on the first ReadableStream.read(), the read is continued until the read status is done.

### CODE REVIEW

**Comment by bdbenim** [comment]
I'm getting the following error:

```
Uncaught (in promise) TypeError: j is undefined
    onreadystatechange moz-extension://60cdd1f5-0bb9-48ef-9099-53044f6f94c9/userscripts/Stash-upload-helper.user.js?id=f138b191-fc61-411f-8b64-13dc0c8f3256:186
eval:185:33
```

The issue is that since `j` is defined within the `try` block, the two if statements testing the `status` after the `catch` block error if there is an exception while trying to parse the JSON text. I think if you move those into the `try` block it should solve that issue.

**Comment by TamalesEnMiPinata** [comment]
> I'm getting the following error:
> 
> ```
> Uncaught (in promise) TypeError: j is undefined
>     onreadystatechange moz-extension://60cdd1f5-0bb9-48ef-9099-53044f6f94c9/userscripts/Stash-upload-helper.user.js?id=f138b191-fc61-411f-8b64-13dc0c8f3256:186
> eval:185:33
> ```
> 
> The issue is that since `j` is defined within the `try` block, the two if statements testing the `status` after the `catch` block error if there is an exception while trying to parse the JSON text. I think if you move those into the `try` block it should solve that issue.

It sounds like `j` was null when it got dereferenced on with `j.status`. I'm not sure what would lead to it being null but I added a null check. Let me know what you think or if you want it changed.

**Comment by bdbenim** [comment]
Looks good to me, it's catching the error now.

It seems to be caused by `text` sometimes containing two JSON responses concatenated together, for example:

```
{"status": "success", "data": {"message": "Uploading cover"}}{"status": "success", "data": {"message": "Uploading contact sheet"}}
```

Mostly this was because I disabled uploading images while debugging, so I guess those responses were being sent at essentially the same moment. Turning image uploading back on resolved that 99%, but it still happens periodically. Doesn't seem to be a huge concern since it just means those two responses will get ignored, but I'm wondering if this is why I've occasionally had the script just not fill out the upload form.

**Comment by TamalesEnMiPinata** [comment]
That's...interesting. So the problem that I was trying to solve was that the ReadableStream.read() didn't contain the entire Stash response but it sounds like the ReadableStream.read() buffer can actually contain two pieces of the response. I'm not sure how to resolve that but there is probably some fancy JSON parsing that can be done identify two unique chunks of JSON in the response. Any ideas?

**Comment by bdbenim** [comment]
I found [this function](https://gist.github.com/jgornick/3786127?permalink_comment_id=4535234#gistcomment-4535234) which seems to do it by counting opening and closing braces. But then the rest of the code would still have to be modified to loop over the resulting list of JSON objects since it's currently only expecting one at a time

**Comment by TamalesEnMiPinata** [comment]
Yeah I think something like that needs to be done here. Do you want me to do it as part of this PR (probably won't get to this for a few days) or should we create an issue and do it in a different PR?

**Comment by bdbenim** [comment]
I think a new issue/PR makes sense. It's a separate problem, though very related, and I think this PR fully resolves the issue you were originally trying to fix and there's no reason not to merge it now

**Pull request merged**
